/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0c0e11',
        'on-primary-fixed-variant': '#004f53',
        'primary-container': '#00f2fe',
        'surface-container-high': '#282a2e',
        'error-container': '#93000a',
        'outline-variant': '#3a494b',
        'on-surface': '#e2e2e7',
        error: '#ffb4ab',
        'primary-fixed-dim': '#00dce6',
        surface: '#111417',
        'on-secondary': '#003919',
        secondary: '#f5fff3',
        'on-background': '#e2e2e7',
        'surface-bright': '#37393d',
        primary: '#e0fdff',
        outline: '#849495',
        'surface-dim': '#111417',
        'tertiary-fixed': '#f0dbff',
        'on-tertiary-fixed': '#2c0051',
        'surface-container-highest': '#333538',
        'surface-container': '#1e2023',
        'on-secondary-fixed': '#00210c',
        'on-tertiary-container': '#852cd3',
        'inverse-on-surface': '#2e3034',
        'surface-variant': '#333538',
        'inverse-surface': '#e2e2e7',
        'tertiary-fixed-dim': '#ddb7ff',
        'secondary-fixed-dim': '#00e478',
        'secondary-fixed': '#60ff98',
        'on-error': '#690005',
        'on-surface-variant': '#b9cacb',
        'tertiary-container': '#ebd1ff',
        'surface-container-low': '#1a1c1f',
        'on-primary-fixed': '#002022',
        'primary-fixed': '#6ff6ff',
        'on-primary': '#00373a',
        'surface-tint': '#00dce6',
        'on-error-container': '#ffdad6',
        background: '#111417',
        'on-tertiary': '#490080',
        'on-secondary-fixed-variant': '#005227',
        'secondary-container': '#34ff8c',
        'on-tertiary-fixed-variant': '#6900b3',
        'inverse-primary': '#00696f',
        tertiary: '#fef4ff',
        'on-secondary-container': '#007239',
        'on-primary-container': '#006a70',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1.25rem',
        margin: '3rem',
        'space-2xl': '4rem',
        'gutter-sm': '1rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'metric-mono': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'display-hero': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '700' }],
        'metric-mono': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
